os: osx
osx_image: xcode10
language: swift

addons:
  homebrew:
    update: true
    packages:
      - jq
      - swiftformat

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - ./bin/continuousintegration
